### ISSUE TITLE
Header captions and logo are invisible on white background

### ISSUE THREAD

**Issue by Furrman** [TwardyFitnessCenter/TwardyFitnessCenter.github.io#38]
At this moment header works awesome but there is a problem with white background. I was planning to use it in many sections on app and we need to do something with it.
Possible options:
- header captions will change to black for white background
- header outside first section will have black transparent panel
- our white background will be replaced with different colors.

I recommend to go with option 2. The best would be to change opacity to 50% when we are outside intro section. The best would be by changing `background: rgba(20, 20, 20, 0.5)`

Could you also remove resizing header. Now on scroll it is changing height which is unecessary I think.

**Comment by konrad88k** [comment]
- [ ] Change logo 'margin-right' to 3rem.
