### ISSUE TITLE
Add subheader to intro section

### ISSUE THREAD

**Issue by Furrman** [TwardyFitnessCenter/TwardyFitnessCenter.github.io#39]
I am planning to add subheader to first section on top of our video. The subheader was: "Nie ma półśrodków".
There are two things to do:
- For big screans it should be somewhere at the right. Maybe at the right bottom corner. I believe in your UI skills and you will know where to put it. The only things I am planning is to split text into two rows like:
NIE MA
PÓŁŚRODKÓW
and align this text to the right.
(eventually you can split all words into separate lines)
- Make PÓŁŚRODKÓW yellow collor like the one we are using on selecting nav element
- For phones etc we have video in the center of screen which means we have top part and bottom free. Top is already reserved for header but bottom I believe is a place for us. I think the text should be centralized and looks like follows:
NIE MA PÓŁŚRODKÓW

Also - can you add TWARDY FITNESS CENTER next to the logo on big screens? We have a lot of space and I think it would be good to have the name visible.

**Comment by konrad88k** [comment]
I set up text centered on intro-movie. There is 2 examples of color/font variety.
For now I leave it as in first image to figure out placement after editing video.

![2](https://user-images.githubusercontent.com/105243490/208815045-b77176e7-589b-4e1b-abff-485f0a6dc2ac.png)
![1](https://user-images.githubusercontent.com/105243490/208815008-fe356497-1454-445f-982e-81e0e5775f79.png)

**Comment by konrad88k** [comment]
I suggest cut off black lines on top and bottom and parts of video which contains text, logo etc. to clean view from too much distracting points.
