### ISSUE TITLE
Can't push branch from local repository.

### ISSUE THREAD

**Issue by konrad88k** [TwardyFitnessCenter/TwardyFitnessCenter.github.io#45]
I created new local branch for #38 issue and I can't push changes to remote repository.
I have exactly the same problem as in this topic:
https://forums.balena.io/t/git-push-stuck-on-writing-objects/1751/20

@Furrman Could you check if you have same problem or maybe it have something in common with last changes?

**Comment by Furrman** [comment]
@konrad88k lets make a call and sort it out together
