### ISSUE TITLE
Find a solution for presenting people metamorphoses

### ISSUE THREAD

**Issue by Furrman** [TwardyFitnessCenter/TwardyFitnessCenter.github.io#7]
Need to find a good solution to show people transformation before working with Twardy and after to show result of cooperation with Twardy

**Comment by Furrman** [comment]
My proposition would be to open a picture in kind of popup and depending on X axis of the mouse one picture would transform into another. Need html example of this.

**Comment by konrad88k** [comment]
Maybe we could use that as a starting point:
https://www.w3schools.com/howto/howto_js_image_comparison.asp

**Comment by Furrman** [comment]
It is okay at this moment - we can close issue
